#!/bin/bash

startBuild()
{
ECR_REPO=891377352857.dkr.ecr.us-east-1.amazonaws.com/nexus-services
DOCKER_BUILD_TAG=$GIT_BRANCH-${BUILD_NUMBER}
docker build -t $ECR_REPO:$DOCKER_BUILD_TAG --pull=true .
if [ $? -eq 0 ]; then
echo "Docker build got success"
else
echo "Docker build was failed"
exit 1
fi
docker images -q $ECR_REPO
GET_LOGIN=$(aws ecr get-login --no-include-email --region us-east-1 --profile new-kaaylabs)
IMAGE_ID=$(docker images -q $ECR_REPO | awk "NR==1{print $1}")
echo $IMAGE_ID
docker tag $IMAGE_ID $ECR_REPO:latest
docker inspect $IMAGE_ID
echo $GET_LOGIN
$GET_LOGIN
docker push $ECR_REPO:$DOCKER_BUILD_TAG && docker push $ECR_REPO:latest
if [ $? -eq 0 ]; then
echo "Docker Push got success"
docker logout
else
echo "Docker Push was failed"
docker logout
exit 1
fi
}


if [[ "$GIT_BRANCH" == "development" || "$GIT_BRANCH" == "uat" || "$GIT_BRANCH" == "preprod" ]];
then
aws s3 cp s3://kaaylabs-operations-new/config/gig-street-api/.env . --profile new-kaaylabs
aws s3 cp s3://kaaylabs-operations-new/config/gig-street-api/gig-street-api-qa/cashfree-publicKey.pem . --profile new-kaaylabs
DevBuild
elif [[ "$GIT_BRANCH" == "main" ]];
then
aws s3 cp s3://kaaylabs-operations-new/config/nexus-squared-ai/.env . --profile new-kaaylabs
startBuild
else
echo "Skipping a build process because this branch is not permitted for docker build: ${GIT_BRANCH}"
fi